// Hypixel liefert Item-NBT im 1.8-Format, d.h. "id" ist eine numerische Legacy-ID.
// Diese Map deckt die IDs ab, die in SkyBlock tatsaechlich vorkommen.
// Ergebnis ist ein Texturname aus den Vanilla-Assets ("item/..." oder "block/...").

const LEGACY_IDS: Record<number, string> = {
  1: "block/stone",
  2: "block/grass_block_top",
  3: "block/dirt",
  4: "block/cobblestone",
  5: "block/oak_planks",
  12: "block/sand",
  13: "block/gravel",
  14: "block/gold_ore",
  15: "block/iron_ore",
  16: "block/coal_ore",
  17: "block/oak_log",
  18: "block/oak_leaves",
  19: "block/sponge",
  20: "block/glass",
  21: "block/lapis_ore",
  22: "block/lapis_block",
  24: "block/sandstone",
  35: "block/white_wool",
  41: "block/gold_block",
  42: "block/iron_block",
  45: "block/bricks",
  46: "block/tnt_side",
  47: "block/bookshelf",
  48: "block/mossy_cobblestone",
  49: "block/obsidian",
  50: "block/torch",
  52: "block/spawner",
  54: "block/oak_planks",
  56: "block/diamond_ore",
  57: "block/diamond_block",
  58: "block/crafting_table_top",
  60: "block/farmland",
  73: "block/redstone_ore",
  74: "block/redstone_ore",
  79: "block/ice",
  80: "block/snow",
  81: "block/cactus_side",
  82: "block/clay",
  84: "block/jukebox_side",
  86: "block/pumpkin_side",
  87: "block/netherrack",
  88: "block/soul_sand",
  89: "block/glowstone",
  91: "block/pumpkin_side",
  95: "block/white_stained_glass",
  97: "block/stone",
  98: "block/stone_bricks",
  99: "block/brown_mushroom_block",
  100: "block/red_mushroom_block",
  101: "block/iron_bars",
  103: "block/melon_side",
  110: "block/mycelium_top",
  112: "block/nether_bricks",
  116: "block/enchanting_table_top",
  120: "block/end_portal_frame_top",
  121: "block/end_stone",
  129: "block/emerald_ore",
  133: "block/emerald_block",
  137: "block/command_block_front",
  138: "block/beacon",
  145: "block/anvil",
  152: "block/redstone_block",
  153: "block/nether_quartz_ore",
  155: "block/quartz_block_side",
  159: "block/white_terracotta",
  165: "block/slime_block",
  168: "block/prismarine_bricks",
  169: "block/sea_lantern",
  170: "block/hay_block_side",
  172: "block/terracotta",
  173: "block/coal_block",
  174: "block/packed_ice",
  179: "block/red_sandstone",

  256: "item/iron_shovel",
  257: "item/iron_pickaxe",
  258: "item/iron_axe",
  259: "item/flint_and_steel",
  260: "item/apple",
  261: "item/bow",
  262: "item/arrow",
  263: "item/coal",
  264: "item/diamond",
  265: "item/iron_ingot",
  266: "item/gold_ingot",
  267: "item/iron_sword",
  268: "item/wooden_sword",
  269: "item/wooden_shovel",
  270: "item/wooden_pickaxe",
  271: "item/wooden_axe",
  272: "item/stone_sword",
  273: "item/stone_shovel",
  274: "item/stone_pickaxe",
  275: "item/stone_axe",
  276: "item/diamond_sword",
  277: "item/diamond_shovel",
  278: "item/diamond_pickaxe",
  279: "item/diamond_axe",
  280: "item/stick",
  281: "item/bowl",
  282: "item/mushroom_stew",
  283: "item/golden_sword",
  284: "item/golden_shovel",
  285: "item/golden_pickaxe",
  286: "item/golden_axe",
  287: "item/string",
  288: "item/feather",
  289: "item/gunpowder",
  290: "item/wooden_hoe",
  291: "item/stone_hoe",
  292: "item/iron_hoe",
  293: "item/diamond_hoe",
  294: "item/golden_hoe",
  295: "item/wheat_seeds",
  296: "item/wheat",
  297: "item/bread",
  298: "item/leather_helmet",
  299: "item/leather_chestplate",
  300: "item/leather_leggings",
  301: "item/leather_boots",
  302: "item/chainmail_helmet",
  303: "item/chainmail_chestplate",
  304: "item/chainmail_leggings",
  305: "item/chainmail_boots",
  306: "item/iron_helmet",
  307: "item/iron_chestplate",
  308: "item/iron_leggings",
  309: "item/iron_boots",
  310: "item/diamond_helmet",
  311: "item/diamond_chestplate",
  312: "item/diamond_leggings",
  313: "item/diamond_boots",
  314: "item/golden_helmet",
  315: "item/golden_chestplate",
  316: "item/golden_leggings",
  317: "item/golden_boots",
  318: "item/flint",
  319: "item/porkchop",
  320: "item/cooked_porkchop",
  321: "item/painting",
  322: "item/golden_apple",
  323: "item/oak_sign",
  325: "item/bucket",
  326: "item/water_bucket",
  327: "item/lava_bucket",
  328: "item/minecart",
  329: "item/saddle",
  331: "item/redstone",
  332: "item/snowball",
  333: "item/oak_boat",
  334: "item/leather",
  335: "item/milk_bucket",
  336: "item/brick",
  337: "item/clay_ball",
  338: "item/sugar_cane",
  339: "item/paper",
  340: "item/book",
  341: "item/slime_ball",
  344: "item/egg",
  345: "item/compass",
  346: "item/fishing_rod",
  347: "item/clock",
  348: "item/glowstone_dust",
  349: "item/cod",
  350: "item/cooked_cod",
  351: "item/ink_sac",
  352: "item/bone",
  353: "item/sugar",
  354: "item/cake",
  356: "item/repeater",
  357: "item/cookie",
  359: "item/shears",
  360: "item/melon_slice",
  361: "item/pumpkin_seeds",
  362: "item/melon_seeds",
  363: "item/beef",
  364: "item/cooked_beef",
  365: "item/chicken",
  366: "item/cooked_chicken",
  367: "item/rotten_flesh",
  368: "item/ender_pearl",
  369: "item/blaze_rod",
  370: "item/ghast_tear",
  371: "item/gold_nugget",
  372: "item/nether_wart",
  373: "item/potion",
  374: "item/glass_bottle",
  375: "item/spider_eye",
  376: "item/fermented_spider_eye",
  377: "item/blaze_powder",
  378: "item/magma_cream",
  379: "item/brewing_stand",
  380: "item/cauldron",
  381: "item/ender_eye",
  382: "item/glistering_melon_slice",
  383: "item/egg",
  384: "item/experience_bottle",
  385: "item/fire_charge",
  386: "item/writable_book",
  387: "item/written_book",
  388: "item/emerald",
  389: "item/item_frame",
  390: "item/flower_pot",
  391: "item/carrot",
  392: "item/potato",
  393: "item/baked_potato",
  394: "item/poisonous_potato",
  395: "item/map",
  396: "item/golden_carrot",
  397: "item/player_head",
  398: "item/carrot_on_a_stick",
  399: "item/nether_star",
  400: "item/pumpkin_pie",
  401: "item/firework_rocket",
  402: "item/firework_star",
  403: "item/enchanted_book",
  404: "item/comparator",
  405: "item/nether_brick",
  406: "item/quartz",
  409: "item/prismarine_shard",
  410: "item/prismarine_crystals",
  411: "item/rabbit",
  412: "item/cooked_rabbit",
  413: "item/rabbit_stew",
  414: "item/rabbit_foot",
  415: "item/rabbit_hide",
  416: "item/armor_stand",
  417: "item/iron_horse_armor",
  418: "item/golden_horse_armor",
  419: "item/diamond_horse_armor",
  420: "item/lead",
  421: "item/name_tag",
  423: "item/mutton",
  424: "item/cooked_mutton",
  425: "block/white_wool",
};

const ASSET_VERSION = "1.21.4";
const ASSET_BASE = `https://raw.githubusercontent.com/InventivetalentDev/minecraft-assets/${ASSET_VERSION}/assets/minecraft/textures`;

/** Texturname zu einer Item-ID (numerisch oder Name) ermitteln. */
export function textureName(material: string): string | null {
  if (!material) return null;
  const asNumber = Number(material);
  if (Number.isFinite(asNumber)) return LEGACY_IDS[asNumber] ?? null;

  const clean = material.replace("minecraft:", "").toLowerCase();
  if (!clean) return null;
  // Namen ohne Präfix landen im item-Ordner; Blöcke fängt die Legacy-Map ab.
  return `item/${clean}`;
}

export function itemIconUrl(material: string): string | null {
  const name = textureName(material);
  if (!name) return null;
  return `${ASSET_BASE}/${name}.png`;
}

export function headIconUrl(textureHash: string, size = 64): string {
  return `https://mc-heads.net/head/${textureHash}/${size}`;
}

export function skinBodyUrl(uuid: string): string {
  return `https://crafatar.com/renders/body/${uuid}?overlay&scale=8`;
}

export function skinFaceUrl(uuid: string, size = 64): string {
  return `https://crafatar.com/avatars/${uuid}?overlay&size=${size}`;
}
